export const UPDATE_COUNTRY = "UPDATE_COUNTRY"
export const UPDATE_BAND = "UPDATE_BAND"
export const UPDATE_GENRE = "UPDATE_GENRE"
export const UPDATE_LABEL = "UPDATE_LABEL"

export const UPDATE_NAME =   "UPDATE_NAME"
export const UPDATE_YEAR =   "UPDATE_YEAR"

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'
export const FETCH_LABELS = 'FETCH_LABELS'
export const FETCH_BANDS = 'FETCH_BANDS'
export const FETCH_GENRES = 'FETCH_GENRES'

export const ADD_DISC = 'ADD_DISC'
export const REMOVE_DISC = 'REMOVE_DISC'
export const BEGIN_ADD_DISC = 'BEGIN_ADD_DISC'
export const ADD_DISC_SUCCESS = 'ADD_DISC_SUCCESS'
export const ADD_DISC_FAILURE = 'ADD_DISC_FAILURE'


export const ADD_TRACK = 'ADD_TRACK'
export const REMOVE_TRACK = 'REMOVE_TRACK'
export const BEGIN_ADD_TRACK = 'BEGIN_ADD_TRACK'
export const ADD_TRACK_SUCCESS = 'ADD_TRACK_SUCCESS'
export const ADD_TRACK_FAILURE = 'ADD_TRACK_FAILURE'
export const SET_LOADING = 'SET_LOADING'
export const ADD_IMAGE = 'ADD_IMAGE'
export const SET_IMAGE = 'SET_IMAGE'
export const SET_FINISHED = 'SET_FINISHED'
